version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./.env:/app/.env
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
      - mailhog
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=mydb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_USER=null
      - MAIL_PASSWORD=null
      - MAIL_FROM=no-reply@example.com
      - MAIL_SECURE=false
      - JWT_SECRET=yourSecretKey

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default
      - shared-network

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  db-data:

networks:
  shared-network:
    external: true
