{
 "title": "GraphQL Engine Event & Cron Trigger",
 "description": "The collection of Hasura Event and Cron trigger metrics",
 "tags": [ "hasura" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Source", "query": "Prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(hasura_http_connections,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(hasura_http_connections{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "event_source",
    "label": "Event Source",
    "query": {
     "query": "label_values(hasura_event_processed_total{job=~\"$job\",instance=~\"$instance\"},source_name)"
    }
   },
   {
    "name": "trigger_name",
    "label": "Event name",
    "query": {
     "query": "label_values(hasura_event_processed_total{job=~\"$job\",instance=~\"$instance\",source_name=~\"$event_source\"},trigger_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Golden Signals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Processed Events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hasura_event_processed_total{job=~\"$job\",instance=~\"$instance\",source_name=~\"$event_source\",trigger_name=~\"$trigger_name\",status=\"success\"}[$__range]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(hasura_event_processed_total{job=~\"$job\",instance=~\"$instance\",source_name=~\"$event_source\",trigger_name=~\"$trigger_name\"}[$__range]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Latency (P95)",
   "type": "stat",
   "description": "P95 latency of Hasura event triggers",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_event_processing_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",source_name=~\"$event_source\",trigger_name=~\"$trigger_name\"}[$__range])) by (le))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "HTTP Workers",
   "type": "gauge",
   "description": "Saturation (No. of HTTP workers for event triggers)",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hasura_event_trigger_http_workers{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Total Processed Cron Events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hasura_cron_events_processed_total{job=~\"$job\",instance=~\"$instance\",status=\"success\"}[$__range]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(hasura_cron_events_processed_total{job=~\"$job\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Event Trigger Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Top Processed Events",
   "type": "table",
   "description": "Top processed event triggers",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, sum by (job,source_name,trigger_name) (increase(hasura_event_processed_total{job=~\"$job\",instance=~\"$instance\",source_name=~\"$event_source\",trigger_name=~\"$trigger_name\"}[$__range]))) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Event Error Rate",
   "type": "table",
   "description": "Top error rate of processed event triggers",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, sum by (job,source_name,trigger_name) (increase(hasura_event_processed_total{job=~\"$job\",instance=~\"$instance\",source_name=~\"$event_source\",trigger_name=~\"$trigger_name\",status=\"failed\"}[$__range])) \n/ sum by (job,source_name,trigger_name) (increase(hasura_event_processed_total{job=~\"$job\",instance=~\"$instance\",source_name=~\"$event_source\",trigger_name=~\"$trigger_name\"}[$__range]))\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Event Latency (P95)",
   "type": "table",
   "description": "Top P95 latency of processed event triggers",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, histogram_quantile(0.95, sum(rate(hasura_event_processing_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",source_name=~\"$event_source\",trigger_name=~\"$trigger_name\"}[$__range])) by (job,source_name, trigger_name, le)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Processing Rate ",
   "type": "timeseries",
   "description": "Processed event triggers rate per interval",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job,source_name,trigger_name) (rate(hasura_event_processed_total{job=~\"$job\",instance=~\"$instance\",source_name=~\"$event_source\",trigger_name=~\"$trigger_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}} - {{trigger_name}} ({{source_name}})"
    }
   ]
  },
  {
   "title": "Event Failure Rate ",
   "type": "timeseries",
   "description": "The failure rate of processed event triggers ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (job,source_name,trigger_name) (rate(hasura_event_processed_total{job=~\"$job\",instance=~\"$instance\",source_name=~\"$event_source\",trigger_name=~\"$trigger_name\",status=\"failed\"}[$__rate_interval]))",
     "legendFormat": "{{job}} - {{trigger_name}} ({{source_name}})"
    }
   ]
  },
  {
   "title": "Event Processing Latency (P95)",
   "type": "timeseries",
   "description": "P95 latency of processed event triggers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_event_processing_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",source_name=~\"$event_source\",trigger_name=~\"$trigger_name\"}[$__rate_interval])) by (job,source_name, trigger_name, le))",
     "legendFormat": "{{job}} - {{trigger_name}} ({{source_name}})"
    }
   ]
  },
  {
   "title": "Event Webhook Latency (P95)",
   "type": "timeseries",
   "description": "P95 latency of processed external webhooks from event triggers ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_event_webhook_processing_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",source_name=~\"$event_source\",trigger_name=~\"$trigger_name\"}[$__rate_interval])) by (job, source_name, trigger_name, le))",
     "legendFormat": "{{job}} - {{trigger_name}} (source_name)"
    }
   ]
  },
  {
   "title": "Event Fetch Time (P95)",
   "type": "timeseries",
   "description": "P95 latency of fetching a batch of events from the database",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_event_fetch_time_per_batch_seconds_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (job,instance,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Queue Time (P95)",
   "type": "timeseries",
   "description": "P95 latency of the queue time for an event already in the processing queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_event_queue_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",source_name=~\"$event_source\",trigger_name=~\"$trigger_name\"}[$__rate_interval])) by (job,source_name,trigger_name,le))",
     "legendFormat": "{{job}} - {{trigger_name}} ({{source_name}})"
    }
   ]
  },
  {
   "title": "Active Event HTTP Workers",
   "type": "timeseries",
   "description": "Current number of active event trigger HTTP workers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "hasura_event_trigger_http_workers{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{instance=\"{{instance}}\", job=\"{{job}}\"}"
    }
   ]
  },
  {
   "title": "Event Trigger Data Transfer",
   "type": "timeseries",
   "description": "Data Transfer bandwidth of Event Trigger requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(hasura_event_trigger_request_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])  + increase(hasura_event_trigger_response_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cron Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Cron Processing Rate",
   "type": "timeseries",
   "description": "The rate of cron events processed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job,instance) (increase(hasura_cron_events_processed_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Processing Failure Rate",
   "type": "timeseries",
   "description": "The failure rate of cron events processed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job,instance) (increase(hasura_cron_events_processed_total{job=~\"$job\",instance=~\"$instance\",status=\"failed\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Trigger Data Transfer",
   "type": "timeseries",
   "description": "Data Transfer bandwidth of Cron Trigger webhook requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(hasura_scheduled_trigger_request_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])  + increase(hasura_scheduled_trigger_response_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}