services:
  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - monitoring-network
      - shared-network

  grafana:
    image: grafana/grafana-oss:9.5.2
    ports:
      - "8000:8000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_PORT=8000
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=http://localhost:8000
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring-network
      - shared-network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://root:password@db:5432/mydb?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - monitoring-network
      - shared-network

networks:
  monitoring-network:
  shared-network:
    external: true

volumes:
  prometheus-data:
  grafana-data: