import { DataSource } from 'typeorm';
import { User } from '../../modules/users/entity/users.entity';
import { Role } from '../../modules/roles/entity/roles.entity';
import * as bcrypt from 'bcrypt';

export const seedDemoUsers = async (
  dataSource: DataSource,
): Promise<User[]> => {
  const userRepository = dataSource.getRepository(User);
  const roleRepository = dataSource.getRepository(Role);

  const roles = {
    admin: await roleRepository.findOne({ where: { role_name: 'Administrateur' } }),
    pilote: await roleRepository.findOne({ where: { role_name: 'Pilote' } }),
    instructeur: await roleRepository.findOne({ where: { role_name: 'Instructeur' } }),
    technicien: await roleRepository.findOne({ where: { role_name: 'Technicien' } }),
  };

  const hashedPassword = await bcrypt.hash('demo1234', 10);

  const defaultDashboardWidgets = [
    { widgetId: 'weather', visible: true, order: 0, size: 'lg' },
    { widgetId: 'quick-actions', visible: true, order: 1, size: 'sm' },
    { widgetId: 'upcoming-reservations', visible: true, order: 2, size: 'md' },
    { widgetId: 'recent-flights', visible: true, order: 3, size: 'md' },
    { widgetId: 'flight-hours-stats', visible: true, order: 4, size: 'md' },
    { widgetId: 'fleet-availability', visible: true, order: 5, size: 'md' },
    { widgetId: 'articles', visible: true, order: 6, size: 'lg' },
  ];

  const demoUsers = [
    {
      first_name: 'Demo',
      last_name: 'Admin',
      email: 'demo@skycrew.fr',
      password: hashedPassword,
      is2FAEnabled: false,
      isEmailConfirmed: true,
      date_of_birth: new Date('1985-03-15'),
      phone_number: '+33 6 12 34 56 78',
      address: '12 Rue de la Paix, 75002 Paris',
      user_account_balance: 1250.00,
      total_flight_hours: 342,
      email_notifications_enabled: true,
      sms_notifications_enabled: true,
      newsletter_subscribed: true,
      language: 'fr',
      speed_unit: 'kt',
      distance_unit: 'nm',
      timezone: 'Europe/Paris',
      preferred_aerodrome: 'LFPG',
      role: roles.admin,
      dashboard_widgets: defaultDashboardWidgets,
    },
    {
      first_name: 'Jean',
      last_name: 'Dupont',
      email: 'jean.dupont@skycrew.fr',
      password: hashedPassword,
      is2FAEnabled: false,
      isEmailConfirmed: true,
      date_of_birth: new Date('1990-07-22'),
      phone_number: '+33 6 98 76 54 32',
      address: '45 Avenue des Champs-Élysées, 75008 Paris',
      user_account_balance: 780.50,
      total_flight_hours: 156,
      email_notifications_enabled: true,
      sms_notifications_enabled: false,
      newsletter_subscribed: true,
      language: 'fr',
      speed_unit: 'kt',
      distance_unit: 'nm',
      timezone: 'Europe/Paris',
      preferred_aerodrome: 'LFPO',
      role: roles.pilote,
      dashboard_widgets: defaultDashboardWidgets,
    },
    {
      first_name: 'Marie',
      last_name: 'Laurent',
      email: 'marie.laurent@skycrew.fr',
      password: hashedPassword,
      is2FAEnabled: false,
      isEmailConfirmed: true,
      date_of_birth: new Date('1982-11-05'),
      phone_number: '+33 6 45 67 89 01',
      address: '8 Rue Victor Hugo, 69002 Lyon',
      user_account_balance: 2100.00,
      total_flight_hours: 1850,
      email_notifications_enabled: true,
      sms_notifications_enabled: true,
      newsletter_subscribed: true,
      language: 'fr',
      speed_unit: 'kt',
      distance_unit: 'nm',
      timezone: 'Europe/Paris',
      preferred_aerodrome: 'LFLL',
      role: roles.instructeur,
      dashboard_widgets: defaultDashboardWidgets,
    },
    {
      first_name: 'Pierre',
      last_name: 'Martin',
      email: 'pierre.martin@skycrew.fr',
      password: hashedPassword,
      is2FAEnabled: false,
      isEmailConfirmed: true,
      date_of_birth: new Date('1978-04-18'),
      phone_number: '+33 6 23 45 67 89',
      address: '22 Boulevard de la Liberté, 59000 Lille',
      user_account_balance: 0,
      total_flight_hours: 0,
      email_notifications_enabled: true,
      sms_notifications_enabled: false,
      newsletter_subscribed: false,
      language: 'fr',
      timezone: 'Europe/Paris',
      role: roles.technicien,
      dashboard_widgets: defaultDashboardWidgets,
    },
    {
      first_name: 'Sophie',
      last_name: 'Bernard',
      email: 'sophie.bernard@skycrew.fr',
      password: hashedPassword,
      is2FAEnabled: false,
      isEmailConfirmed: true,
      date_of_birth: new Date('1995-01-30'),
      phone_number: '+33 6 11 22 33 44',
      address: '5 Place Bellecour, 69002 Lyon',
      user_account_balance: 450.00,
      total_flight_hours: 78,
      email_notifications_enabled: true,
      sms_notifications_enabled: false,
      newsletter_subscribed: true,
      language: 'fr',
      speed_unit: 'km/h',
      distance_unit: 'km',
      timezone: 'Europe/Paris',
      preferred_aerodrome: 'LFLL',
      role: roles.pilote,
      dashboard_widgets: defaultDashboardWidgets,
    },
    {
      first_name: 'Lucas',
      last_name: 'Moreau',
      email: 'lucas.moreau@skycrew.fr',
      password: hashedPassword,
      is2FAEnabled: false,
      isEmailConfirmed: true,
      date_of_birth: new Date('1988-09-12'),
      phone_number: '+33 6 55 66 77 88',
      address: '17 Quai des Chartrons, 33000 Bordeaux',
      user_account_balance: 1580.00,
      total_flight_hours: 520,
      email_notifications_enabled: true,
      sms_notifications_enabled: true,
      newsletter_subscribed: true,
      language: 'fr',
      speed_unit: 'kt',
      distance_unit: 'nm',
      timezone: 'Europe/Paris',
      preferred_aerodrome: 'LFBD',
      role: roles.pilote,
      dashboard_widgets: defaultDashboardWidgets,
    },
    {
      first_name: 'Camille',
      last_name: 'Petit',
      email: 'camille.petit@skycrew.fr',
      password: hashedPassword,
      is2FAEnabled: false,
      isEmailConfirmed: true,
      date_of_birth: new Date('1992-06-25'),
      phone_number: '+33 6 99 88 77 66',
      address: '3 Rue du Vieux Port, 13001 Marseille',
      user_account_balance: 920.00,
      total_flight_hours: 2400,
      email_notifications_enabled: true,
      sms_notifications_enabled: true,
      newsletter_subscribed: true,
      language: 'fr',
      speed_unit: 'kt',
      distance_unit: 'nm',
      timezone: 'Europe/Paris',
      preferred_aerodrome: 'LFML',
      role: roles.instructeur,
      dashboard_widgets: defaultDashboardWidgets,
    },
    {
      first_name: 'Thomas',
      last_name: 'Leroy',
      email: 'thomas.leroy@skycrew.fr',
      password: hashedPassword,
      is2FAEnabled: false,
      isEmailConfirmed: true,
      date_of_birth: new Date('1975-12-08'),
      phone_number: '+33 6 44 33 22 11',
      address: '9 Rue de la République, 31000 Toulouse',
      user_account_balance: 0,
      total_flight_hours: 0,
      email_notifications_enabled: true,
      sms_notifications_enabled: false,
      newsletter_subscribed: false,
      language: 'fr',
      timezone: 'Europe/Paris',
      role: roles.technicien,
      dashboard_widgets: defaultDashboardWidgets,
    },
    {
      first_name: 'Emma',
      last_name: 'Girard',
      email: 'emma.girard@skycrew.fr',
      password: hashedPassword,
      is2FAEnabled: false,
      isEmailConfirmed: true,
      date_of_birth: new Date('1998-02-14'),
      phone_number: '+33 6 77 88 99 00',
      address: '28 Avenue Jean Jaurès, 44000 Nantes',
      user_account_balance: 200.00,
      total_flight_hours: 32,
      email_notifications_enabled: true,
      sms_notifications_enabled: false,
      newsletter_subscribed: true,
      language: 'fr',
      speed_unit: 'kt',
      distance_unit: 'nm',
      timezone: 'Europe/Paris',
      preferred_aerodrome: 'LFRS',
      role: roles.pilote,
      dashboard_widgets: defaultDashboardWidgets,
    },
    {
      first_name: 'Antoine',
      last_name: 'Roux',
      email: 'antoine.roux@skycrew.fr',
      password: hashedPassword,
      is2FAEnabled: false,
      isEmailConfirmed: true,
      date_of_birth: new Date('1987-08-03'),
      phone_number: '+33 6 66 55 44 33',
      address: '14 Rue Nationale, 67000 Strasbourg',
      user_account_balance: 3200.00,
      total_flight_hours: 890,
      email_notifications_enabled: true,
      sms_notifications_enabled: true,
      newsletter_subscribed: true,
      language: 'fr',
      speed_unit: 'kt',
      distance_unit: 'nm',
      timezone: 'Europe/Paris',
      preferred_aerodrome: 'LFST',
      role: roles.pilote,
      dashboard_widgets: defaultDashboardWidgets,
    },
  ];

  const savedUsers: User[] = [];

  for (const userData of demoUsers) {
    const existing = await userRepository.findOne({
      where: { email: userData.email },
    });

    if (!existing) {
      const user = userRepository.create(userData);
      const saved = await userRepository.save(user);
      savedUsers.push(saved);
      console.log(`Demo user "${userData.first_name} ${userData.last_name}" created`);
    } else {
      savedUsers.push(existing);
      console.log(`Demo user "${userData.email}" already exists`);
    }
  }

  console.log('Demo users seeding completed');
  return savedUsers;
};
