module.exports = {
  mySidebar: [
    {
      type: 'category',
      label: 'Documentation',
      items: [
        'index',
        'getting-started',
        {
          type: 'category',
          label: 'Références des API',
          items: [
            'api-references',
            {
              type: 'autogenerated',
              dirName: 'types',
            },
            {
              type: 'autogenerated',
              dirName: 'operations',
            },
          ],
        },
        'guides',
        'faq',
      ],
    },
  ],
};
